### PR TITLE
Hide follower-only pinned statuses from logged-out users

### LINKED ISSUE #1178: pinned private replies shown as public
### Steps to reproduce the problem

1. make a public post
2. make a private reply and pin it
3. look at it in a private window and realize you can see the private post without logging in: image
4. despair

### Expected behaviour

be unable to see the post unless logged in

### Actual behaviour

post is visible

### Specifications

v1.0.6+3.5.2

### PR DESCRIPTION
**Pull request by johnholdun**
Fixes #1178

### CODE REVIEW

File: app/controllers/accounts_controller.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def show
         end
 
         if current_user.nil?
-          @pinned_statuses = cache_collection(@account.pinned_statuses.without_local_only, Status) if show_pinned_statuses?
+          @pinned_statuses = cache_collection(filtered_pinned_statuses.without_local_only, Status) if show_pinned_statuses?
```
Comment (johnholdun) [inline app/controllers/accounts_controller.rb:32]: This scoped collection was already defined in the profile—it limits to just pinned statuses that have a visibility of public or unlisted, then the `without_local_only` scope further limits the collection.

File: spec/controllers/accounts_controller_spec.rb [hunk 2]
```diff
@@ -120,6 +120,11 @@
           expect(response.body).to include(I18n.t('stream_entries.pinned'))
         end
 
+        it 'does not render private pinned status' do
```
Comment (johnholdun) [inline spec/controllers/accounts_controller_spec.rb:123]: This spec _should_ pass but something about my local environment was making controller specs raise errors. Something about Webpack not generating a manifest. I'll look into this in the future, but I wanted to make sure this was in here.

**Comment by dariusk** [comment]
Thank you!!
